# Queries for economy
CREATE_MEMBERS_TABLE = "CREATE TABLE IF NOT EXISTS members (id INTEGER PRIMARY KEY, userid INTEGER UNIQUE, name TEXT, money INTEGER, rank TEXT);"
CREATE_RANKS_TABLE = "CREATE TABLE IF NOT EXISTS ranks (id INTEGER PRIMARY KEY, name TEXT UNIQUE, minsalary INTEGER, maxsalary INTEGER, required INTEGER, position INTEGER UNIQUE);"
INSERT_MEMBER = "INSERT INTO members (userid, name, money, rank) VALUES (?, ?, ?, ?);"
INSERT_RANK = "INSERT INTO ranks (name, minsalary, maxsalary, required, position) VALUES (?, ?, ?, ?, ?);"
UPDATE_MEMBER_MONEY = "UPDATE members SET money = ? WHERE userid = ?;"
UPDATE_RANK = "WIP"
GET_ALL_MEMBERS = "SELECT * FROM members;"
GET_ALL_MEMBERS_BY_NETWORTH = "SELECT * FROM members ORDER BY money DESC;"
GET_ALL_RANKS = "SELECT * FROM ranks;"
GET_ALL_RANKS_BY_POSITION = "SELECT * FROM ranks ORDER BY position DESC;"
GET_MEMBER_BY_USERID = "SELECT * FROM members WHERE userid = ?;"
GET_RANK_BY_NAME = "SELECT * FROM ranks WHERE name = ?;"
GET_RANK_BY_POSITION = "SELECT * FROM ranks WHERE position = ?;"
DELETE_MEMBER = "DELETE FROM members WHERE userid = ?;"
DELETE_RANK = "DELETE FROM ranks WHERE name = ?"