CREATE_RPS_TABLE = "CREATE TABLE IF NOT EXISTS rps (id INTEGER PRIMARY KEY, userid INTEGER UNIQUE, name TEXT, rating INTEGER);"
INSERT_RPS_RATING = "INSERT OR REPLACE INTO rps (userid, name, rating) VALUES (?, ?, ?);"
GET_RPS_RATING_BY_USERID ="SELECT * FROM rps WHERE USERID = ?;"
GET_ALL_RATINGS = "SELECT * FROM rps ORDER BY rating DESC;"