import re

class Formatter():

    def format_paragraph(paragraph) -> str:
        paragraph = re.sub(r"\s{2,}", " ", paragraph)
        paragraph = re.sub(r"\s\?", "?", paragraph)
        paragraph = re.sub(r"\s\!", "!", paragraph)
        paragraph = re.sub(r"\s\,", ",", paragraph)
        paragraph = re.sub(r"\s\.", ".", paragraph)
        paragraph = re.sub(r"\?(?=\b[a-zA-Z])", "? ", paragraph)
        paragraph = re.sub(r"\!(?=\b[a-zA-Z])", "! ", paragraph)
        paragraph = re.sub(r"\,(?=\b[a-zA-Z])", ", ", paragraph)
        paragraph = re.sub(r"\.(?=\b[a-zA-Z])", ". ", paragraph)
        paragraph = re.sub(r"\:(?=\b[a-zA-Z])", ": ", paragraph)
        paragraph = re.sub(r"(``|'')", '"', paragraph)
        paragraph = re.sub(r"\r?\n|\r", "", paragraph)
        paragraph = re.sub(r"\s{2,}", " ", paragraph)
        paragraph = re.sub(r'\?\"', "?", paragraph)
        paragraph = re.sub(r'\!\"', "!", paragraph)
        paragraph = re.sub(r'\,\"', ",", paragraph)
        paragraph = re.sub(r'\.\"', ".", paragraph)
        paragraph = re.sub(r'\.\:', ":", paragraph)
        paragraph = re.sub(r";\s;", " ", paragraph)
        paragraph = re.sub(r'"(\s+)([^"]+)(\s+)"', r'"\2"', paragraph)
        paragraph = re.sub(r'\s(?<=\s)"\?', "?", paragraph)
        paragraph = re.sub(r'\s(?<=\s)"\!', "!", paragraph)
        paragraph = re.sub(r'\s(?<=\s)"\,', ",", paragraph)
        paragraph = re.sub(r'\s(?<=\s)"\.', ".", paragraph)
        paragraph = re.sub(r'[\?\!\,\.][\?\!\,\.]', ".", paragraph)
        paragraph = re.sub(r'\(\s([^\)]+)\s\)', r'(\1)', paragraph)
        paragraph = re.sub(r"^\?", "", paragraph)
        paragraph = re.sub(r"^\!", "", paragraph)
        paragraph = re.sub(r"^\,", "", paragraph)
        paragraph = re.sub(r"^\.", "", paragraph)
        paragraph = re.sub(r"--", "-", paragraph)
        paragraph = re.sub(r"\s\)", "", paragraph)
        paragraph = re.sub(r"\(\s", "", paragraph)
        paragraph = re.sub(r'\"', "", paragraph)
        paragraph = re.sub(r"\s{2,}", " ", paragraph)
        paragraph = re.sub(r"^\s+", "", paragraph)
        return paragraph